modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/gigaherz/PackingTape/issues"
license="BSD (3 clause)"

[[mods]]
modId="packingtape"
version="${file.jarVersion}"
displayName="Packing Tape"
description='''
Adds a simple means to carry thigns with you
'''
displayURL="https://github.com/gigaherz/PackingTape"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.packingtape]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2.62-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.packingtape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"