modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/gigaherz/PackingTape/issues"
license="BSD (3 clause)"

[[mods]]
modId="packingtape"
version="${file.jarVersion}"
displayName="Packing Tape"
description='''
Adds a simple means to carry thigns with you
'''
displayURL="https://github.com/gigaherz/PackingTape"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.packingtape]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.packingtape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"